apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
# Core Read
- apiGroups: [""]
  resources: ["services","namespaces"]
  verbs: ["get","watch","list"]

# Patch for Services
- apiGroups: [""]
  resources: ["services", "services/status"]
  verbs: ["patch"]

# CRD Read
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get","list","watch"]

# Framework: admission webhook configuration management.
- apiGroups: ["admissionregistration.k8s.io/v1", "admissionregistration.k8s.io/v1beta1"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["create", "patch"]

# Events  
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

# Kopf
- apiGroups: ["kopf.dev"]
  resources: ["clusterkopfpeerings"]
  verbs: ["list", "watch", "patch", "get"]

# Ingress
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]

- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingresses/status"]
  verbs: ["patch"]